sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.stack"

matrix:
  include:
  - env: GHC='8.8.3'
    os: linux
  - env: GHC='8.8.3'
    os: osx

before_install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh

install:
  # install stack and build project
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version
  - stack build --test --no-run-tests --bench --no-run-benchmarks

script:
  - stack test --no-terminal

notifications:
  email: false
